### ISSUE TITLE
Script does not work

### ISSUE THREAD

**Issue by irfaanaikagjee** [theflakes/sigma_to_wazuh#19]
Hello bro,

The script sigma_to_wazuh.py does not work. I tried using different machines and python versions. Here is the error:

**[root@localhost sigma_to_wazuh]# python3 sigma_to_wazuh.py
[!] ERROR loading rule id tracking file: ./rule_ids.json
Traceback (most recent call last):
  File "sigma_to_wazuh.py", line 961, in <module>
    main()
  File "sigma_to_wazuh.py", line 935, in main
    conditions = convert.fixup_condition(sigma_rule['detection']['condition'])
TypeError: string indices must be integers**

Possible to fix the script plz?

Regards,

**Comment by theflakes** [comment]
I won't be getting back to this for a while most likely. That file its complaining about is a file used for tracking rules from one run of the script to another. You can try deleting it, no idea if that will fix it though.

**Comment by theflakes** [comment]
Took a quick look, found an unfinished sigma rule from their repo was breaking things. Added a catch to ignore broken rules.

Please note though that this script may never be able to convert all the logic in all sigma rules correctly.

**Comment by irfaanaikagjee** [comment]
The script is working fine now. Thank you bro, Great job.
